---

- hosts: server
  become: true
  tasks:

  - name: Remove symlink
    ansible.builtin.file:
      path: /etc/localtime
      state: absent
  
  - name: Create a symbolic link
    ansible.builtin.file:
      src: /usr/share/zoneinfo/Europe/Moscow
      dest: /etc/localtime
      owner: root
      group: root
      state: link

  - name: Restart service chronyd.service
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: chronyd

  - name: install packages
    yum:
      name: epel-release
      state: present

  - name: install packages 
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - nginx
      - vim
      - audispd-plugins

  - name: Copy file nginx.conf
    ansible.builtin.copy:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: '0644'

  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: restarted
      name: nginx
  
  - name: Enable service httpd
    ansible.builtin.systemd:
      name: nginx
      enabled: yes

  - name: Copy file audit.rules
    ansible.builtin.copy:
      src: files/audit.rules
      dest: /etc/audit/rules.d/audit.rules
      owner: root
      group: root
      mode: '0600'

  - name: Copy file auditd.conf
    ansible.builtin.copy:
      src: files/auditd.conf
      dest: /etc/audit/auditd.conf
      owner: root
      group: root
      mode: '0640'

  - name: Copy file au-remote.conf
    ansible.builtin.copy:
      src: files/au-remote.conf
      dest: /etc/audisp/plugins.d/au-remote.conf
      owner: root
      group: root
      mode: '0640'

  - name: Copy file audisp-remote.conf
    ansible.builtin.copy:
      src: files/audisp-remote.conf
      dest: /etc/audisp/audisp-remote.conf
      owner: root
      group: root
      mode: '0640'

  - name: Restart service auditd
    ansible.builtin.command: service auditd restart

#  - name: Restart service auditd
#    ansible.builtin.service:
#      name: auditd
#      state: restarted

- hosts: client
  become: true
  tasks:

  - name: Remove symlink
    ansible.builtin.file:
      path: /etc/localtime
      state: absent
  
  - name: Create a symbolic link
    ansible.builtin.file:
      src: /usr/share/zoneinfo/Europe/Moscow
      dest: /etc/localtime
      owner: root
      group: root
      state: link

  - name: Restart service chronyd.service
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: chronyd

  - name: Copy file rsyslog.conf
    ansible.builtin.copy:
      src: files/rsyslog.conf
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: '0644'

  - name: Restart service rsyslog.service
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: yes
      name: rsyslog.service

  - name: Copy file auditd.conf
    ansible.builtin.copy:
      src: files/client_auditd.conf
      dest: /etc/audit/auditd.conf
      owner: root
      group: root
      mode: '0640'

  - name: Restart service auditd
    ansible.builtin.command: service auditd restart

#  - name: Restart service auditd
#    ansible.builtin.service:
#      name: auditd
#      state: restarted

