#

# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.50.10",
  virtualbox__intnet: "net1"
    server.vm.hostname = "server"
    server.vm.provision "shell", path: "server_script.sh"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.11",
  virtualbox__intnet: "net1"
    client.vm.hostname = "client"
    client.vm.provision "shell", path: "client_script.sh"
  end
end
