# -*- mode: ruby -*-
# vi: set ft=ruby :
# export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
      v.memory = "1024"
  end

  config.vm.define "pxeserver" do |pxeserver|
    pxeserver.vm.disk :disk, size: "15GB", name: "extra_storage"
    pxeserver.vm.network "private_network", ip: "10.0.0.20", virtualbox__intnet: "pxenet"
    pxeserver.vm.network "private_network", ip: "192.168.50.10", adapter: 3
    pxeserver.vm.network "forwarded_port", guest: 80, host: 8081
    pxeserver.vm.hostname = "pxeserver"
  end

  config.vm.define "pxeclient" do |pxeclient|
    pxeclient.vm.box = 'centos/7'
    pxeclient.vm.host_name = 'pxeclient'
    pxeclient.vm.network :private_network, ip: "10.0.0.21"
    pxeclient.vm.provider :virtualbox do |vb|
      vb.memory = "2048"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize [
          'modifyvm', :id,
          '--nic1', 'intnet',
          '--intnet1', 'pxenet',
          '--nic2', 'nat',
          '--boot1', 'net',
          '--boot2', 'none',
          '--boot3', 'none',
          '--boot4', 'none'
        ]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end

#  config.vm.define "client" do |client|
#    client.vm.network "private_network", ip: "192.168.11.150", virtualbox__intnet: "net"
#    client.vm.hostname = "client"
#  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.host_key_checking = "false"
    ansible.become = "true"
    ansible.limit = "all"
  end

end
