# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
    ansible.playbook = "ansible/playbook.yml"
#    ansible.inventory_path = "ansible/hosts"
    ansible.host_key_checking = "false"
    ansible.become = "true"
    ansible.limit = "all"
  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net"
    server.vm.hostname = "server"
#    server.vm.provision "shell", inline: <<-SHELL
#      echo "Hello"
#    SHELL
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "net"
    client.vm.hostname = "client"
  end

end
